"""initial_schema_with_moviestatus_now_showing

Revision ID: ed44325d752b
Revises: 
Create Date: 2026-07-27 08:50:40.081769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed44325d752b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
